### ISSUE TITLE
API broken: Group Hierarchie

### ISSUE THREAD

**Issue by DumbergerL** [5pm-HDH/churchtools-api#183]
The ChurchTools API Endpoint /api/groups/hierarchies?ids%5B%5D=9 is broken. 

TODO: Create Support Ticket for ChurchTools

**Comment by djschilling** [comment]
I think that is just a misunderstanding.
The returned groups must match all filters. So if the child or the parent is not part of the filter nothing is returned. So if you just provide one Id there cannot be returned anything.

**Comment by djschilling** [comment]
For this use case you can use `/groups/{groupId}/children` or `/groups/{groupId}/parents`
