### ISSUE TITLE
Document Error handling / expected exceptions

### ISSUE THREAD

**Issue by castilma** [5pm-HDH/churchtools-api#51]
It would be nice if you can write down under doc/, or as docstring, what exceptions one should could expect, when 
1. a request times out
2. the domain cannot be resolved
3. the authenticated user is not allowed to see the requested ressource
4. the session cookie/ login token is invalid

**Comment by DumbergerL** [comment]
The Error-Handling-Concept divides an exception in five different categories:

**CTConnectException**
- technical Exception the ConnectException from Guzzle
- error in Connection (timeout, undefined-host, ...)

**CTConfigException**
- wrong Configuration (e.q. no API-Url is set)

**CTAuthException**
- could not authenticate user
- unauthorized access to resource

**CTRequestException**
- could not retrieve the models

**CTModelException**
- exception in model (e.q. process wiki-pages return root node)
