### ISSUE TITLE
Pagination does not work

### ISSUE THREAD

**Issue by naitsirch** [5pm-HDH/churchtools-api#68]
I am trying to load persons in a paginated style. But it looks like this does not work.

```php
$persons = PersonRequest::where('page', 1)
            ->where('limit', 10)
            ->get();
```

It always loads all persons. As far as I understand the reason is that the conditions are not added as query params to the request.

**Edit**
Right after sending this issue, I noticed that the Pagination trait iterates over all pages and merges them.
Isn't there a way to limit the result to one page?

**Comment by DumbergerL** [comment]
@naitsirch Thanks for your Issue and Pull-Request! I appreciate! I added a simple unit-test to cover the code and it worked fine! 
I moved the documentation to a sub-page. I hope you are fine with this.

**Comment by naitsirch** [comment]
Yes, of course! Thanks for merging.
