### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by DumbergerL** [5pm-HDH/churchtools-api#7]
before pull request / on master branch:
- composer validation

execute test suite:
- copy "tests/testdata.example.ini" to "tests/testdata.ini"
- replace values with repository secrets
- run phpunit tests

**Comment by staubichsauger** [comment]
Unit tests should not depend on any external system. Requiring access to an actual church tools server and valid user credentials to run them is not good practice. The respective API requests should be mocked and injected for running the unit tests. What you are doing with some of the tests are integration tests, which are great, but not part of general unit testing. Unit tests need to be repeatable for everyone without requiring any external dependencies (servers, DB, real credentials, ...).

**Comment by staubichsauger** [comment]
I commented out all "integration tests" to be able to run phpunit in the gh action.
