### ISSUE TITLE
security fix for guzzlehttp/guzzle

### ISSUE THREAD

**Issue by piridium** [5pm-HDH/churchtools-api#70]
Some days ago, guzzlehttp/guzzle released v7.4.3 containing a fix for a vulnerability with severity score 8/10. For more details see here: https://github.com/advisories/GHSA-cwmx-hcrq-mhc3

## Issue
churchtools-api requires "guzzlehttp/guzzle": "7.3.*" in composer.json, preventing the dependency to incorporate this fix.

## Possible fix
Please consider to require "guzzlehttp/guzzle:^7" - if compatible - to get all fixes for the 7.x major version.

**Comment by DumbergerL** [comment]
@piridium Thanks for your hint! I fixed it and with the PR #71.
If you have some Feature-Request or find some other bug don't hesitate to create another Issue.

**Comment by piridium** [comment]
@DumbergerL You're welcome. I'll be happy to do so.
Thank you for your work on the project!
