### ISSUE TITLE
The "GuzzleHttp\Client" class is considered final

### ISSUE THREAD

**Issue by naitsirch** [5pm-HDH/churchtools-api#82]
I am getting this deprecation notice:

> User Deprecated: The "GuzzleHttp\Client" class is considered final. It may change without further notice as of its next major version. You should not extend it from "CTApi\CTClient".

One should switch from inheritence to composition in the client.

**Comment by DumbergerL** [comment]
Thank you very much @naitsirch for this Issue! I refactored the relation between CTClient and GuzzleClient from inheritance to composition, like you suggested.

**Comment by naitsirch** [comment]
Wow, thank you :-)
Keep up the great work.
