### ISSUE TITLE
Refactor: Check HTTP-Status in CTClient instead of RequestBuilder

### ISSUE THREAD

**Issue by DumbergerL** [5pm-HDH/churchtools-api#97]
The AbstractRequestBuilder contains code to validate the Http-Status-Code:

```php
// AbstractRequestBuilder.php
public function delete(string $modelId): void
{
    $url = $this->getApiEndpoint() . '/' . $modelId;

    $client = CTClient::getClient();
    $response = $client->delete($url);

    if (!in_array($response->getStatusCode(), [200, 204])) {
        throw CTRequestException::ofErrorResponse($response);
    }
}
```

and 

```php
// AbstractRequestBuilder.php
protected function updateData(string $objectId, array $data): void
{
    $url = $this->getApiEndpoint() . '/' . $objectId;

    $client = CTClient::getClient();
    $response = $client->patch($url, ['json' => $data]);

    if ($response->getStatusCode() !== 200) {
        throw CTRequestException::ofErrorResponse($response);
    }
}
```

I think it would be better to handle the HTTP-Status Code in the CTClient itself. For this reason i created the `handleResponse` function that is called by every POST, GET, PATCH and DELETE-Method:

```php
// CTClient.php
private function handleResponse(ResponseInterface $response): ResponseInterface
{
    switch ($response->getStatusCode()) {
        case 401:
            throw new CTAuthException("Unauthorized.", 401);
    }
    return $response;
}
```

If neccessary we could also add a second "HTTP-Method" parameter to handle distinguish HTTP-Methods differently:
```php
private function handleResponse(ResponseInterface $reponse, string $httpMethod): ResponseInterface {}
```
But i think a good first shot could be to throw a `CTRequestException::ofErrorResponse($response)` for every status code that is not between 200 and 299.

**Comment by DumbergerL** [comment]
@naitsirch This refactoring belongs to parts of your code so im thankful for your feedback. What do you think of this refactoring? Does it make sense to you?
Im also totally opened if you have a diffrent mind on this.

**Comment by naitsirch** [comment]
Yes, that makes absolutely sense to me ;-)
